# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI_LAUNCHER.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LAUNCHER_MainWindow(object):
    def setupUi(self, LAUNCHER_MainWindow):
        LAUNCHER_MainWindow.setObjectName("LAUNCHER_MainWindow")
        LAUNCHER_MainWindow.resize(1200, 804)
        self.centralwidget = QtWidgets.QWidget(LAUNCHER_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.background_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_label.setMouseTracking(False)
        self.background_label.setTabletTracking(False)
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap(".\\image/icon/background_launcher.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(1070, 730, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 17pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(255, 85, 127, 220)")
        self.exit_button.setText("")
        self.exit_button.setObjectName("exit_button")
        self.emo_button = QtWidgets.QPushButton(self.centralwidget)
        self.emo_button.setGeometry(QtCore.QRect(100, 170, 431, 551))
        self.emo_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emo_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 17pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(255, 85, 127, 220)")
        self.emo_button.setText("")
        self.emo_button.setObjectName("emo_button")
        self.doctor_button = QtWidgets.QPushButton(self.centralwidget)
        self.doctor_button.setGeometry(QtCore.QRect(670, 170, 431, 551))
        self.doctor_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doctor_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 17pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(255, 85, 127, 220)")
        self.doctor_button.setText("")
        self.doctor_button.setObjectName("doctor_button")
        LAUNCHER_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LAUNCHER_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(LAUNCHER_MainWindow)

    def retranslateUi(self, LAUNCHER_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        LAUNCHER_MainWindow.setWindowTitle(_translate("LAUNCHER_MainWindow", "MainWindow"))
