# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI_DOCTOR.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DOCTOR_MainWindow(object):
    def setupUi(self, DOCTOR_MainWindow):
        DOCTOR_MainWindow.setObjectName("DOCTOR_MainWindow")
        DOCTOR_MainWindow.resize(1200, 804)
        self.centralwidget = QtWidgets.QWidget(DOCTOR_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.background_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_label.setMouseTracking(False)
        self.background_label.setTabletTracking(False)
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap(".\\image/icon/background_doctor.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.response_text = QtWidgets.QTextEdit(self.centralwidget)
        self.response_text.setGeometry(QtCore.QRect(30, 30, 681, 491))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setItalic(False)
        self.response_text.setFont(font)
        self.response_text.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 14pt \"Roboto\";\n"
"border-radius: 0px;")
        self.response_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.response_text.setReadOnly(True)
        self.response_text.setObjectName("response_text")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(230, 569, 481, 201))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setItalic(False)
        self.input_text.setFont(font)
        self.input_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_text.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 14pt \"Roboto\";\n"
"border-radius: 0px;")
        self.input_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.input_text.setMarkdown("")
        self.input_text.setObjectName("input_text")
        self.switch_button = QtWidgets.QPushButton(self.centralwidget)
        self.switch_button.setGeometry(QtCore.QRect(757, 653, 71, 41))
        self.switch_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.switch_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\image/icon/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.switch_button.setIcon(icon)
        self.switch_button.setIconSize(QtCore.QSize(80, 40))
        self.switch_button.setAutoRepeat(False)
        self.switch_button.setObjectName("switch_button")
        self.switch_label = QtWidgets.QLabel(self.centralwidget)
        self.switch_label.setGeometry(QtCore.QRect(862, 653, 71, 41))
        self.switch_label.setText("")
        self.switch_label.setPixmap(QtGui.QPixmap(".\\image/icon/keyboard.png"))
        self.switch_label.setScaledContents(True)
        self.switch_label.setObjectName("switch_label")
        self.upload_button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_button.setGeometry(QtCore.QRect(1094, 150, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setItalic(False)
        self.upload_button.setFont(font)
        self.upload_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 15pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(111, 220, 227);")
        self.upload_button.setText("")
        self.upload_button.setObjectName("upload_button")
        self.history_button = QtWidgets.QPushButton(self.centralwidget)
        self.history_button.setGeometry(QtCore.QRect(1013, 645, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setItalic(False)
        self.history_button.setFont(font)
        self.history_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 15pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(16, 44, 87);")
        self.history_button.setObjectName("history_button")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(750, 730, 50, 50))
        self.send_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.send_button.setText("")
        self.send_button.setObjectName("send_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(820, 730, 51, 51))
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.reset_button.setText("")
        self.reset_button.setObjectName("reset_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(1060, 730, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 17pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(255, 85, 127, 220)")
        self.exit_button.setObjectName("exit_button")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(990, 20, 171, 61))
        self.time_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 36pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(255,255,255);")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        self.location_label.setGeometry(QtCore.QRect(770, 80, 171, 31))
        self.location_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 14pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        self.weather_label = QtWidgets.QLabel(self.centralwidget)
        self.weather_label.setGeometry(QtCore.QRect(760, 0, 100, 100))
        self.weather_label.setStyleSheet("")
        self.weather_label.setText("")
        self.weather_label.setScaledContents(True)
        self.weather_label.setObjectName("weather_label")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(880, 35, 61, 41))
        self.temp_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 24pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.robot_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.robot_label_2.setGeometry(QtCore.QRect(20, 570, 181, 201))
        self.robot_label_2.setText("")
        self.robot_label_2.setPixmap(QtGui.QPixmap(".\\image/icon/8757478.png"))
        self.robot_label_2.setScaledContents(True)
        self.robot_label_2.setObjectName("robot_label_2")
        self.emer_button = QtWidgets.QPushButton(self.centralwidget)
        self.emer_button.setGeometry(QtCore.QRect(910, 730, 61, 51))
        self.emer_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emer_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.emer_button.setText("")
        self.emer_button.setObjectName("emer_button")
        self.day_label = QtWidgets.QLabel(self.centralwidget)
        self.day_label.setGeometry(QtCore.QRect(990, 75, 171, 41))
        self.day_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 500 12pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(255,255,255);")
        self.day_label.setAlignment(QtCore.Qt.AlignCenter)
        self.day_label.setObjectName("day_label")
        self.temp_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.temp_label_2.setGeometry(QtCore.QRect(930, 30, 31, 21))
        self.temp_label_2.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 14pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.temp_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label_2.setObjectName("temp_label_2")
        self.precision_label = QtWidgets.QLabel(self.centralwidget)
        self.precision_label.setGeometry(QtCore.QRect(1035, 410, 121, 61))
        self.precision_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none; \n"
"font: italic 700 20pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.precision_label.setAlignment(QtCore.Qt.AlignCenter)
        self.precision_label.setObjectName("precision_label")
        self.skin_text = QtWidgets.QLabel(self.centralwidget)
        self.skin_text.setGeometry(QtCore.QRect(755, 570, 415, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setItalic(True)
        self.skin_text.setFont(font)
        self.skin_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none; \n"
"font: italic 500 12pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(0, 0, 0,200);\n"
"border-radius: 10px;")
        self.skin_text.setAlignment(QtCore.Qt.AlignCenter)
        self.skin_text.setObjectName("skin_text")
        self.capture_button = QtWidgets.QPushButton(self.centralwidget)
        self.capture_button.setGeometry(QtCore.QRect(1100, 250, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setItalic(False)
        self.capture_button.setFont(font)
        self.capture_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.capture_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 15pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(111, 220, 227);")
        self.capture_button.setText("")
        self.capture_button.setObjectName("capture_button")
        self.webcam_label = QtWidgets.QLabel(self.centralwidget)
        self.webcam_label.setGeometry(QtCore.QRect(750, 143, 260, 195))
        self.webcam_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none; \n"
"font: italic 700 20pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.webcam_label.setText("")
        self.webcam_label.setScaledContents(True)
        self.webcam_label.setObjectName("webcam_label")
        self.webcam_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.webcam_label_2.setGeometry(QtCore.QRect(755, 405, 208, 156))
        self.webcam_label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none; \n"
"font: italic 700 20pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.webcam_label_2.setText("")
        self.webcam_label_2.setScaledContents(True)
        self.webcam_label_2.setObjectName("webcam_label_2")
        DOCTOR_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DOCTOR_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(DOCTOR_MainWindow)

    def retranslateUi(self, DOCTOR_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        DOCTOR_MainWindow.setWindowTitle(_translate("DOCTOR_MainWindow", "MainWindow"))
        self.response_text.setPlaceholderText(_translate("DOCTOR_MainWindow", "Phản hồi từ Doctor"))
        self.input_text.setHtml(_translate("DOCTOR_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:14pt; font-weight:800; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.input_text.setPlaceholderText(_translate("DOCTOR_MainWindow", "Câu hỏi của người dùng"))
        self.history_button.setText(_translate("DOCTOR_MainWindow", "        LỊCH SỬ"))
        self.exit_button.setText(_translate("DOCTOR_MainWindow", "THOÁT"))
        self.time_label.setText(_translate("DOCTOR_MainWindow", "14:22"))
        self.location_label.setText(_translate("DOCTOR_MainWindow", "TP. Hà Nội"))
        self.temp_label.setText(_translate("DOCTOR_MainWindow", "27"))
        self.day_label.setText(_translate("DOCTOR_MainWindow", "T3, 19/06/2024"))
        self.temp_label_2.setText(_translate("DOCTOR_MainWindow", "o"))
        self.precision_label.setText(_translate("DOCTOR_MainWindow", "96,54%"))
        self.skin_text.setText(_translate("DOCTOR_MainWindow", "Melanoma - Ung thư hắc tố da"))
