# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI_EMO.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EMO_MainWindow(object):
    def setupUi(self, EMO_MainWindow):
        EMO_MainWindow.setObjectName("EMO_MainWindow")
        EMO_MainWindow.resize(1200, 804)
        self.centralwidget = QtWidgets.QWidget(EMO_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.background_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_label.setMouseTracking(False)
        self.background_label.setTabletTracking(False)
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap(".\\image/icon/background_emo.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.response_text = QtWidgets.QTextEdit(self.centralwidget)
        self.response_text.setGeometry(QtCore.QRect(30, 30, 760, 450))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setItalic(False)
        self.response_text.setFont(font)
        self.response_text.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 14pt \"Roboto\";\n"
"border-radius: 0px;")
        self.response_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.response_text.setReadOnly(True)
        self.response_text.setObjectName("response_text")
        self.robot_label = QtWidgets.QLabel(self.centralwidget)
        self.robot_label.setGeometry(QtCore.QRect(840, 340, 141, 141))
        self.robot_label.setText("")
        self.robot_label.setPixmap(QtGui.QPixmap(".\\image/icon/robot.png"))
        self.robot_label.setScaledContents(True)
        self.robot_label.setObjectName("robot_label")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(20, 530, 180, 181))
        self.user_label.setText("")
        self.user_label.setPixmap(QtGui.QPixmap(".\\image/icon/user.png"))
        self.user_label.setScaledContents(True)
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.user_lineEdit.setGeometry(QtCore.QRect(40, 730, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setItalic(False)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setMouseTracking(False)
        self.user_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.user_lineEdit.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 14pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);")
        self.user_lineEdit.setText("")
        self.user_lineEdit.setFrame(True)
        self.user_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_lineEdit.setReadOnly(True)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(230, 520, 560, 250))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setItalic(False)
        self.input_text.setFont(font)
        self.input_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_text.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 14pt \"Roboto\";\n"
"border-radius: 0px;")
        self.input_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.input_text.setMarkdown("")
        self.input_text.setObjectName("input_text")
        self.switch_button = QtWidgets.QPushButton(self.centralwidget)
        self.switch_button.setGeometry(QtCore.QRect(855, 530, 120, 60))
        self.switch_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switch_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.switch_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\image/icon/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.switch_button.setIcon(icon)
        self.switch_button.setIconSize(QtCore.QSize(120, 60))
        self.switch_button.setAutoRepeat(False)
        self.switch_button.setObjectName("switch_button")
        self.switch_label = QtWidgets.QLabel(self.centralwidget)
        self.switch_label.setGeometry(QtCore.QRect(1030, 530, 120, 60))
        self.switch_label.setText("")
        self.switch_label.setPixmap(QtGui.QPixmap(".\\image/icon/keyboard.png"))
        self.switch_label.setScaledContents(True)
        self.switch_label.setObjectName("switch_label")
        self.upload_button = QtWidgets.QPushButton(self.centralwidget)
        self.upload_button.setGeometry(QtCore.QRect(830, 620, 165, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setItalic(False)
        self.upload_button.setFont(font)
        self.upload_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 15pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(111, 220, 227);")
        self.upload_button.setObjectName("upload_button")
        self.history_button = QtWidgets.QPushButton(self.centralwidget)
        self.history_button.setGeometry(QtCore.QRect(1013, 626, 165, 70))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setItalic(False)
        self.history_button.setFont(font)
        self.history_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 800 15pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(16, 44, 87);")
        self.history_button.setObjectName("history_button")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(820, 730, 50, 50))
        self.send_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.send_button.setText("")
        self.send_button.setObjectName("send_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(897, 730, 51, 51))
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.reset_button.setText("")
        self.reset_button.setObjectName("reset_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(1060, 730, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        self.exit_button.setFont(font)
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 17pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgba(255, 85, 127, 220)")
        self.exit_button.setObjectName("exit_button")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(1010, 20, 171, 61))
        self.time_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 36pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(255,255,255);")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        self.location_label.setGeometry(QtCore.QRect(830, 80, 171, 31))
        self.location_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 14pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        self.weather_label = QtWidgets.QLabel(self.centralwidget)
        self.weather_label.setGeometry(QtCore.QRect(830, 0, 100, 100))
        self.weather_label.setStyleSheet("")
        self.weather_label.setText("")
        self.weather_label.setScaledContents(True)
        self.weather_label.setObjectName("weather_label")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(920, 35, 61, 41))
        self.temp_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 24pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.robot_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.robot_label_2.setGeometry(QtCore.QRect(840, 150, 330, 330))
        self.robot_label_2.setText("")
        self.robot_label_2.setPixmap(QtGui.QPixmap(".\\image/icon/robot.png"))
        self.robot_label_2.setScaledContents(True)
        self.robot_label_2.setObjectName("robot_label_2")
        self.emer_button = QtWidgets.QPushButton(self.centralwidget)
        self.emer_button.setGeometry(QtCore.QRect(970, 730, 61, 51))
        self.emer_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emer_button.setStyleSheet("background-color: transparent; border: none; \n"
"")
        self.emer_button.setText("")
        self.emer_button.setObjectName("emer_button")
        self.day_label = QtWidgets.QLabel(self.centralwidget)
        self.day_label.setGeometry(QtCore.QRect(1010, 75, 171, 41))
        self.day_label.setStyleSheet("background-color: transparent; border: none; \n"
"font: 500 12pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(255,255,255);")
        self.day_label.setAlignment(QtCore.Qt.AlignCenter)
        self.day_label.setObjectName("day_label")
        self.temp_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.temp_label_2.setGeometry(QtCore.QRect(970, 25, 31, 21))
        self.temp_label_2.setStyleSheet("background-color: transparent; border: none; \n"
"font: 700 14pt \"Roboto\";\n"
"border-radius: 0px;\n"
"color: rgb(248, 246, 227);")
        self.temp_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label_2.setObjectName("temp_label_2")
        self.background_label.raise_()
        self.response_text.raise_()
        self.user_label.raise_()
        self.user_lineEdit.raise_()
        self.input_text.raise_()
        self.switch_button.raise_()
        self.switch_label.raise_()
        self.upload_button.raise_()
        self.history_button.raise_()
        self.send_button.raise_()
        self.reset_button.raise_()
        self.exit_button.raise_()
        self.time_label.raise_()
        self.location_label.raise_()
        self.weather_label.raise_()
        self.temp_label.raise_()
        self.robot_label_2.raise_()
        self.robot_label.raise_()
        self.emer_button.raise_()
        self.day_label.raise_()
        self.temp_label_2.raise_()
        EMO_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EMO_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(EMO_MainWindow)

    def retranslateUi(self, EMO_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        EMO_MainWindow.setWindowTitle(_translate("EMO_MainWindow", "MainWindow"))
        self.response_text.setPlaceholderText(_translate("EMO_MainWindow", "Phản hồi từ EMO"))
        self.user_lineEdit.setPlaceholderText(_translate("EMO_MainWindow", "Tên người dùng"))
        self.input_text.setHtml(_translate("EMO_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:14pt; font-weight:800; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.input_text.setPlaceholderText(_translate("EMO_MainWindow", "Câu hỏi của người dùng"))
        self.upload_button.setText(_translate("EMO_MainWindow", "        TẢI LÊN"))
        self.history_button.setText(_translate("EMO_MainWindow", "        LỊCH SỬ"))
        self.exit_button.setText(_translate("EMO_MainWindow", "THOÁT"))
        self.time_label.setText(_translate("EMO_MainWindow", "14:22"))
        self.location_label.setText(_translate("EMO_MainWindow", "TP. Hà Nội"))
        self.temp_label.setText(_translate("EMO_MainWindow", "27"))
        self.day_label.setText(_translate("EMO_MainWindow", "T3, 19/06/2024"))
        self.temp_label_2.setText(_translate("EMO_MainWindow", "o"))
